version: '3.9'

services:
  frontend:
    build:
      context: ./frontend/recruti_front  # Le chemin vers votre dossier frontend
      dockerfile: Dockerfile
    container_name: recruti_frontend
    ports:
      - "4200:80"  # Mappe le port 80 du conteneur (Nginx) au port 4200 de votre machine
    #volumes:
     # - ./frontend/recruti_front:/app # Monte le dossier du projet dans le conteneur pour le développement en temps réel
     # - /app/node_modules # Monte le dossier du projet dans le conteneur, mais ignore node_modules pour éviter les conflits
    depends_on:
      - backend  # Le frontend dépend du backend, mais attendre n'est pas critique
    networks:
      - app-network
    env_file:
      - ./frontend/recruti_front/.env
    restart: always

  mysql:
    image: mysql:8.0
    container_name: mysql
    environment:
      MYSQL_DATABASE: springBase
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    build:
      context: ./backend/recruti_backend
      dockerfile: Dockerfile
    container_name: recruti_backend
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/springBase
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
      SPRING_DEVTOOLS_RESTART_ENABLED: true
    ports:
      - "9091:8080"
    depends_on:
      mysql:
        condition: service_healthy
    networks:
      - app-network
    env_file:
      - ./backend/recruti_backend/.env
    volumes:
    - uploads_data:/uploads 


networks:
  app-network:

volumes:
  mysql_data:
  uploads_data:   
